version: '3.9'

services:
  # MongoDB
  mongodb:
    image: mongo:4.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: khanhnp
    ports:
      - 27017:27017
    volumes:
      - ./app-backend/mongodb-data:/data/db
  
  # Mongo Express
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: khanhnp
      ME_CONFIG_MONGODB_SERVER: mongodb 