version: '3.9'

services:
  backend-app:
    build:
      context: ./mission-mng
      dockerfile: ./mission-mng/docker-config/Dockerfile
    container_name: backend-app
    working_dir: /var/www/html
    ports: 80:80
    volumes:
      - ./mission-mng:/var/www/html
      - ./mission-mng/docker-config/nginx/nginx_log:/var/log/nginx
      - ./mission-mng/docker-config/php-fpm:/var/log/php-fpm.log
      - ./mission-mng/docker-config/nginx/config.d/app.conf:/etc/nginx/conf.d/app.conf
    links:
      - mongodb
  # Mongo
  mongodb:
    image: mongo:4.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: khanhnp
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-data:/data/db
  
  # Mongo Express
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: khanhnp
      ME_CONFIG_MONGODB_SERVER: mongodb 